INSERT INTO categories (name) VALUES
  ('Entremets aux fruits'),
  ('Entremets au chocolat'),
  ('Number cake'),
  ('Tartes'),
  ('Les classiques'),
  ('Gâteaux à thème'),
  ('Macarons'),
  ('Mignardises'),
  ('Cupcakes'),
  ('Traiteur');

INSERT INTO articles (category_id, slug, title, subtitle, cover_image_key, slices, price, details_html) VALUES
((SELECT id FROM categories WHERE name='Entremets aux fruits'),
 'fraisier',
 'Fraisier',
 'Génoise moelleuse, crème mousseline vanille et fraises fraîches de saison.',
 'fraisier.webp',
 '8,10,12,25',
 4.00,
 '<p>Notre fraisier signature, monté à la main avec une génoise imbibée d''un léger sirop de kirsch et une crème mousseline à la vanille de Madagascar.</p><p>Décor pâte d''amande disponible sur demande.</p>'),

((SELECT id FROM categories WHERE name='Entremets aux fruits'),
 'framboisier',
 'Framboisier',
 'Biscuit aux amandes, mousse vanille et framboises fraîches.',
 'framboisier.webp',
 '8,10,12,25',
 4.00,
 '<p>Un entremets fruité et léger, parfait pour les beaux jours. Insert de coulis de framboise pour intensifier la saveur.</p>'),

((SELECT id FROM categories WHERE name='Entremets aux fruits'),
 'la-seraphine',
 'La Séraphine',
 'Création maison : croustillant praliné, mousse fruits rouges et coeur framboise.',
 'la-seraphine.webp',
 '8,10,12,25',
 4.00,
 '<p>Une recette imaginée par la maison, équilibrée entre l''onctuosité de la mousse aux fruits rouges et le croquant du praliné.</p>');

INSERT INTO articles (category_id, slug, title, subtitle, cover_image_key, slices, price, details_html) VALUES
((SELECT id FROM categories WHERE name='Entremets au chocolat'),
 'trois-choco',
 'Trois chocolats',
 'Mousse au chocolat noir, lait et blanc sur un croustillant praliné.',
 'trois-choco.webp',
 '8,10,12,25',
 4.00,
 '<p>L''indétrônable trois chocolats : trois mousses aériennes superposées sur une base biscuit cacao et feuilletine praliné.</p>'),

((SELECT id FROM categories WHERE name='Entremets au chocolat'),
 'le-royal',
 'Le Royal',
 'Biscuit succès, croustillant praliné et mousse au chocolat noir.',
 'le-royal.webp',
 '8,10,12,25',
 4.00,
 '<p>Le grand classique français revisité avec un chocolat noir de couverture 70%.</p>'),

((SELECT id FROM categories WHERE name='Entremets au chocolat'),
 'charlotte-poire-chocolat',
 'Charlotte poire-chocolat',
 'Biscuit cuillère, mousse chocolat noir et poires pochées au sirop.',
 'charlotte-poire-chocolat.webp',
 '8,10,12',
 4.00,
 '<p>Une charlotte gourmande et élégante, idéale pour les grandes tablées.</p>'),

((SELECT id FROM categories WHERE name='Entremets au chocolat'),
 'schuss',
 'Schuss',
 'Mousse chocolat noir intense, insert caramel et biscuit moelleux.',
 'schuss.webp',
 '8,10,12',
 4.00,
 '<p>Un entremets puissant en cacao, contrasté par un caramel beurre salé fondant.</p>');

INSERT INTO articles (category_id, slug, title, subtitle, cover_image_key, slices, price, details_html) VALUES
((SELECT id FROM categories WHERE name='Number cake'),
 'number-cake',
 'Number Cake',
 'Sablé breton, crème diplomate vanille et fruits frais — chiffre au choix.',
 'numberCakeE.webp',
 '8,10,12',
 4.50,
 '<p>Personnalisable avec le chiffre ou la lettre de votre choix. <strong>+0,50 €/part</strong> pour un thème spécifique (décor sucre, fleurs comestibles, fruits exotiques...).</p>');

INSERT INTO articles (category_id, slug, title, subtitle, cover_image_key, slices, price, details_html) VALUES
((SELECT id FROM categories WHERE name='Tartes'),
 'tarte-au-citron',
 'Tarte au citron meringuée',
 'Pâte sablée, crème au citron de Menton et meringue italienne dorée.',
 'tarte-au-citron.webp',
 '6,8',
 3.80,
 '<p>Acidulée et fondante, notre tarte au citron est meringuée à la demande pour conserver son croquant.</p>');

INSERT INTO articles (category_id, slug, title, subtitle, cover_image_key, slices, price, details_html) VALUES
((SELECT id FROM categories WHERE name='Les classiques'),
 'paris-brest',
 'Paris-Brest',
 'Couronne de pâte à choux, crème mousseline pralinée et amandes effilées.',
 'paris-brest.webp',
 '8,10,12',
 3.80,
 '<p>Notre praliné est réalisé maison à partir de noisettes du Piémont torréfiées.</p>'),

((SELECT id FROM categories WHERE name='Les classiques'),
 'flan-vanille-bourbon',
 'Flan vanille Bourbon',
 'Pâte brisée croustillante et appareil onctueux à la vanille Bourbon.',
 'flan-vanille-bourbon.webp',
 '8,10',
 3.80,
 '<p>Un flan généreux, gratiné comme il se doit, garni à la vraie gousse de vanille.</p>'),

((SELECT id FROM categories WHERE name='Les classiques'),
 'giga-eclair',
 'Giga éclair',
 'Éclair format XXL — chocolat, café ou vanille — à partager.',
 'giga-eclair.webp',
 '6,8,10',
 3.80,
 '<p>Un éclair géant pour vos goûters d''anniversaire. Précisez le parfum à la commande.</p>'),

((SELECT id FROM categories WHERE name='Les classiques'),
 'biscoff',
 'Entremets Biscoff',
 'Mousse au spéculoos, croustillant biscuit caramélisé et insert caramel.',
 'biscoff.webp',
 '8,10,12',
 3.80,
 '<p>L''incontournable Biscoff revisité en entremets aérien.</p>');

INSERT INTO articles (category_id, slug, title, subtitle, cover_image_key, slices, price, details_html) VALUES
((SELECT id FROM categories WHERE name='Gâteaux à thème'),
 'theme-cake',
 'Gâteau à thème personnalisé',
 'Décor entièrement fait main selon votre univers : mariage, anniversaire, baby shower...',
 'theme-cake.webp',
 '10,12,15,20,25',
 5.50,
 '<p>Tarif à partir de 5,50 €/part selon la complexité du décor. <strong>Plaque décor fait main : +10 €</strong>. <strong>Photo en sucre / disque : +10 €</strong>.</p><p>Contactez-nous au moins 10 jours avant la date souhaitée.</p>'),

((SELECT id FROM categories WHERE name='Gâteaux à thème'),
 'tinycake',
 'Tiny Cake',
 'Mini-gâteau décoré, format individuel ou duo, idéal pour une demande spéciale.',
 'tinycake.webp',
 '2,4',
 5.50,
 '<p>Format mignon et personnalisable, parfait pour une demande en mariage, un gender reveal ou un cadeau gourmand.</p>');

INSERT INTO articles (category_id, slug, title, subtitle, cover_image_key, slices, price, details_html) VALUES
((SELECT id FROM categories WHERE name='Macarons'),
 'macaron-coeur-framboise',
 'Macarons coeur framboise',
 'Coques aux amandes, ganache chocolat blanc et insert framboise fraîche.',
 'macaron-coeur-framboise.webp',
 '10',
 10.00,
 '<p>Lot de 10 macarons identiques. D''autres parfums disponibles sur demande : vanille, pistache, caramel, café, chocolat...</p>'),

((SELECT id FROM categories WHERE name='Macarons'),
 'macaron-tower',
 'Pièce montée de macarons',
 'Tour de macarons multicolores pour vos mariages et grands événements.',
 'macaron-tower.webp',
 '30,50,80,100',
 1.00,
 '<p>Tarif à la pièce. Précisez le nombre et les parfums souhaités. Support et présentation inclus.</p>');

INSERT INTO articles (category_id, slug, title, subtitle, cover_image_key, slices, price, details_html) VALUES
((SELECT id FROM categories WHERE name='Mignardises'),
 'mignardises',
 'Assortiment de mignardises',
 'Petites bouchées sucrées variées pour buffets et fins de repas.',
 'mignardises.webp',
 '10',
 13.00,
 '<p>Lot de 10 mignardises identiques (tartelettes, éclairs, choux, opéras...). Précisez le parfum à la commande.</p>'),

((SELECT id FROM categories WHERE name='Mignardises'),
 'popcake',
 'Pop cakes',
 'Petites sucettes de gâteau enrobées de chocolat, décorées à la main.',
 'popcake.webp',
 '10',
 13.00,
 '<p>Idéales pour les goûters d''enfants et les candy bars.</p>'),

((SELECT id FROM categories WHERE name='Mignardises'),
 'minidonuts',
 'Mini donuts',
 'Donuts moelleux glacés, assortiment de couleurs au choix.',
 'minidonuts.webp',
 '10',
 13.00,
 '<p>Lot de 10 mini donuts identiques. Plusieurs glaçages disponibles.</p>'),

((SELECT id FROM categories WHERE name='Mignardises'),
 'giga-cookie-trois-choco',
 'Giga cookie trois chocolats',
 'Cookie géant aux trois chocolats à partager, façon mookie.',
 'giga-cookie-trois-choco.webp',
 '6,8',
 13.00,
 '<p>Servi tiède au coeur fondant sur demande.</p>');

INSERT INTO articles (category_id, slug, title, subtitle, cover_image_key, slices, price, details_html) VALUES
((SELECT id FROM categories WHERE name='Cupcakes'),
 'cupcakes-perso',
 'Cupcakes personnalisés',
 'Topping crème au beurre coloré, décor sur mesure pour vos thèmes.',
 'cupcakesPerso.webp',
 '5,10',
 10.00,
 '<p>15 € le lot de 5 grands cupcakes — 10 € le lot de 10 petits cupcakes.</p><p>Choisissez votre parfum (vanille, chocolat, red velvet, citron...) et votre thème de décoration.</p>');

INSERT INTO articles (category_id, slug, title, subtitle, cover_image_key, slices, price, details_html) VALUES
((SELECT id FROM categories WHERE name='Traiteur'),
 'mini-burger',
 'Mini-burgers',
 'Petits pains briochés maison, steak et cheddar fondant.',
 'mini-burger.webp',
 '20',
 16.00,
 '<p>Lot de 20 pièces identiques. Parfait pour un cocktail dînatoire.</p>'),

((SELECT id FROM categories WHERE name='Traiteur'),
 'mini-kebab',
 'Mini-kebabs',
 'Pains pita maison, viande marinée et sauce blanche.',
 'mini-kebab.webp',
 '20',
 16.00,
 '<p>Lot de 20 pièces. Servis froids ou tièdes selon votre événement.</p>'),

((SELECT id FROM categories WHERE name='Traiteur'),
 'navette-fraicheur',
 'Navettes fraîcheur',
 'Petits pains briochés garnis de crudités, saumon ou poulet.',
 'navette-fraicheur.webp',
 '20',
 16.00,
 '<p>Garniture au choix à préciser à la commande. Lot de 20 navettes.</p>'),

((SELECT id FROM categories WHERE name='Traiteur'),
 'plateau-traiteur',
 'Plateau traiteur assorti',
 'Sélection variée de bouchées salées (verrines, navettes, pics...).',
 'traiteur.webp',
 '20,30,50',
 16.00,
 '<p>Composé à la demande selon vos goûts et le nombre de convives.</p>');